services:
  redis:
    image: 'redis:7.0'
    ports:
      - '6379'
    labels:
      org.springframework.boot.service-connection: redis
      org.springframework.boot.readiness-check.tcp.disable: true